- name: "Deploy PVSO"
  hosts: **************
  gather_facts: no
  become: yes
  become_user: oracle
  vars:
      wozm_new: ~/new-WOZM/wozm*.ear
      backup:
        path: ~/backup_`date +'%d-%m-%Y'`/
        wozm: ~/backup_`date +'%d-%m-%Y'`/wozm/wozm*.ear
        fm-editor: ~/backup_`date +'%d-%m-%Y'`/fm-editor/fm-editor*.war
        fssarm: ~/backup_`date +'%d-%m-%Y'`/fssarm/fssarm.war
      applications: 
        wozm: wozm
        fm-editor: fm-editor
        fssarm: fssarm

  tasks:
    - name: "Kill Nodes"
      shell: "kill -9 $(pgrep -f INSTANCE)"
      ignore_errors: yes

    - name: "Backup files"
      when: inventory_hostname == "*************************"
      shell: "cp -R ~/app/glassfish4/glassfish/domains/wozm/applications/__internal/ {{ backup.path }}"

    - name: "Undeploy applications"
      when: inventory_hostname == "***********************"
      shell: 
        chdir: "/u01/app/glassfish4/glassfish/bin"
        cmd: "{{ item }}"
      ignore_errors: yes
      with_items:
          - "./asadmin --user admin --passwordfile ~/.pfile-glassfish undeploy --target wozmcluster {{ applications.wozm }}"
          - "./asadmin --user admin --passwordfile ~/.pfile-glassfish undeploy --target wozmcluster {{ applications.fm-editor }}"
          - "./asadmin --user admin --passwordfile ~/.pfile-glassfish undeploy --target wozmcluster {{ applications.fssarm }}"

    - name: Pause for 15 seconds to undeploy app cache
      pause:
        seconds: 15

    # - name: Pause for 15 seconds to undeploy app cache
    #   shell: "sleep 15"    

    - name: "Start Nodes"
      shell:
        chdir: "/u01/app/glassfish4/glassfish/bin"
        cmd: "./asadmin --user admin --passwordfile ~/.pfile-glassfish   start-local-instance --sync=full"

    - name: "Deploy applications"
      shell:
        chdir: "/u01/app/glassfish4/glassfish/bin"
        cmd: "{{ item }}"
      ignore_errors: yes
      with_items:
          - "./asadmin --user admin --passwordfile ~/.pfile-glassfish deploy --contextroot fm-editor  --name fm-editor --force=true --target wozmcluster {{ backup.fm-editor }}"
          - "./asadmin --user admin --passwordfile ~/.pfile-glassfish deploy --contextroot fssarm  --name faasrm --force=true --target wozmcluster {{ backup.fssarm }}"
          - "./asadmin --user admin --passwordfile ~/.pfile-glassfish deploy --force=true --target wozmcluster --name wozm {{ wozm_new }}"
